// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8POI8aoHQh_2kFIaztZpmzx4oygPXVJA',
    appId: '1:841539008369:web:2ecb9692b15fb65305e8d0',
    messagingSenderId: '841539008369',
    projectId: 'school-survey-364d3',
    authDomain: 'school-survey-364d3.firebaseapp.com',
    storageBucket: 'school-survey-364d3.firebasestorage.app',
    measurementId: 'G-3P6QHQSH8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQaDUdjqAZRgupFsGZVBBZobmJ10_hrng',
    appId: '1:841539008369:android:f6ce7ffc459ba54a05e8d0',
    messagingSenderId: '841539008369',
    projectId: 'school-survey-364d3',
    storageBucket: 'school-survey-364d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ahwRLXUAwLP1gbtUlaxVwpsyilNqrDk',
    appId: '1:841539008369:ios:72f1608366ab5fc205e8d0',
    messagingSenderId: '841539008369',
    projectId: 'school-survey-364d3',
    storageBucket: 'school-survey-364d3.firebasestorage.app',
    iosBundleId: 'com.example.schoolSurvey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ahwRLXUAwLP1gbtUlaxVwpsyilNqrDk',
    appId: '1:841539008369:ios:72f1608366ab5fc205e8d0',
    messagingSenderId: '841539008369',
    projectId: 'school-survey-364d3',
    storageBucket: 'school-survey-364d3.firebasestorage.app',
    iosBundleId: 'com.example.schoolSurvey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8POI8aoHQh_2kFIaztZpmzx4oygPXVJA',
    appId: '1:841539008369:web:25b145b659b4f39605e8d0',
    messagingSenderId: '841539008369',
    projectId: 'school-survey-364d3',
    authDomain: 'school-survey-364d3.firebaseapp.com',
    storageBucket: 'school-survey-364d3.firebasestorage.app',
    measurementId: 'G-TVCCKW0WKY',
  );

}